### ISSUE TITLE
cannot repeat submit after failure

### ISSUE THREAD

**Issue by dsschult** [WIPACrepo/iceprod#151]
If the json fails to parse, we display a warning message.  But it seems the submit button is now inactive, so we can't easily fix the problem and try again.

Also, it would be handy to display the full error message for json parse failures.  The error console tells the line and column it failed at.  See if that can be shown directly.

**Comment by ddelventhal** [comment]
Seems to be working now. The error from JSON.parse is now displayed on failure. The message may or may not be useful depending on the browser.
