### ISSUE TITLE
Send i/o metrics to graphite: gridftp times to stagein and stageout

### ISSUE THREAD

**Issue by gonzalomerino** [WIPACrepo/iceprod#177]
In order to have more insight to how bad or well are the gridftp in/out transfers doing for iceprod pilots, it will be nice to try and send some metrics for this

may be

for the file stagein and stageout: seconds taken, bytes transferred (then avg. MB/s) and exit status.

**Comment by dsschult** [comment]
There are two ways to do this:

1. Instrument the pilot with graphite probes.  The pilots will be submitting directly to graphite, which may not work everywhere and means that server must be accessible to the world.  Also, this uses UDP, so packets may be dropped on busy networks.

2. Add to task stats.  This would then get rolled into some elasticsearch type thing, which the server would update on every task completion.  Tracking failures would require some re-architecture in iceprod, but doable.

Preferences?

**Comment by dsschult** [comment]
As for the graphite vs elasticsearch debate, I think the separation should be real-time monitoring vs lookups.  Graphite is rrd-like, and great for real-time.  Elasticsearch is better for looking up useful information after the fact.

This feels more like an after the fact lookup to me.

**Comment by gonzalomerino** [comment]
I think option #2 makes more sense.

I aggree in the monitoring vs accounting this is probably more an
accounting item, or a bunch of performance metrics that are associated to a
task once it is completed.

by curiosity, the task stats, are they sent back to Madison via some
iceprod protocol? or you are planning on injecting them as classads with
condor_chirp?

**Comment by dsschult** [comment]
They are sent back as part of the "finished" message, and are currently stored in the iceprod db.  So we have lots of data just sitting there, waiting to be analyzed.
