### ISSUE TITLE
new graphite metric: high memory limit hit, bump requirements up and resubmit events

### ISSUE THREAD

**Issue by gonzalomerino** [WIPACrepo/iceprod#178]
It will be useful to have a metric in graphite that counts these events, when the iceprod pilot detects a job overusing memory, and decides to kill it and resubmit it with larger mem.

We will want to separate cpu and gpu jobs for these counters.

Having also some measure of what was the GB of RAM used, or the new GB required, will also be useful.

**Comment by dsschult** [comment]
There is already a metric that counts when we hit the limit.  CPU vs GPU is not separated though, or what the limit is.

I'm not sure graphite is the best place to track the GB.  Elastic search may be better, where we can just dump json into it.

**Comment by gonzalomerino** [comment]
I agree tracking the GB is not going to be nice in graphite.

But may be tracking as counters these couple of things might be easier, and useful:

- count the number of jobs removed due to memory overuse

- count (add) the number of seconds wasted due to these jobs being killed.

we might want coarser time binning (hourly?) for these plots... I am not sure we gain much by 1minute bins for these.
