### ISSUE TITLE
make task_stats accessible

### ISSUE THREAD

**Issue by dsschult** [WIPACrepo/iceprod#205]
Provide an rpc interface for retrieving the task_stats for a given task_id.

**Comment by dsschult** [comment]
Should be flexible enough to retrieve either the latest entry, or all entries.

**Comment by ddelventhal** [comment]
Currently we have an API for returning all the task_stat data.
In order add the option for returning only the latest entry, we will need some test data to ensure correct operation.

**Comment by dsschult** [comment]
should work fine with the new api
