### ISSUE TITLE
task failure clears job_temp

### ISSUE THREAD

**Issue by jvansanten** [WIPACrepo/iceprod#209]
A job's temporary space appears to be cleared once a task fails 20 times. If the task had dependencies whose output was supposed to be stored in job_temp, then resetting the failed task will only create a task that failed to find its input. If it's possible to know that the job_temp was cleared, then resetting a task should also reset its dependencies.

**Comment by dsschult** [comment]
Clearing the job_temp on task failure is a bug, which I think I've found.  We'll stop doing that.

**Comment by dsschult** [comment]
closed in b17338f
