### ISSUE TITLE
Improved json dataset config validation

### ISSUE THREAD

**Issue by jcdiazvelez** [WIPACrepo/iceprod#232]
If there is an invalid configuration jason, you usually get an error but it's difficult to pinpoint where the error is. Some better diagnostics would help troubleshoot this.

**Comment by ddelventhal** [comment]
Currently the JSON is being parsed client-side. The error message is supplied by the clients web browser, thus it is not always very clear. We could add an RPC to parse the JSON server-side in case of failure, to provide more consistent diagnostics.

**Comment by dsschult** [comment]
Here might be a hint:
https://stackoverflow.com/questions/13323356/parsing-faulty-json-and-be-able-to-display-where-the-error-is
