### ISSUE TITLE
Option to give the total number of jobs when running manually

### ISSUE THREAD

**Issue by javierggt** [WIPACrepo/iceprod#243]
When running manually, there is the '--job' option. With this I can specify which job to run, but the total number of jobs can not be specified (and I guess default to 1). I therefore get errors like trying to get random numbers from more streams than there exist.

**Comment by dsschult** [comment]
Would it be better to have another option to set this, or to just set the total number of jobs equal to the job option (so it works, but isn't exactly the same seed as in production)?

**Comment by dsschult** [comment]
Note that the parameter is added to the config file inside options:
```json
{
  "options": {
    "jobs_submitted": 10000
  }
}
```
So if you really want to manually set it, it can be done.

**Comment by javierggt** [comment]
I think it is better to have another option that if None defaults to the job number.

Right now I just care that it runs, since it is testing, but if the script silently sets the number of jobs to the current number, it could cause inconsistencies and you would not know it (the random streams would be different, for example). It could then happen that someone finishes a dataset by running a few failed jobs by hand.

Now I read your comment about the config file. I think that is a possibility that removes the need for any extra command line option.
