### ISSUE TITLE
Dataset id should be enforced in configuration

### ISSUE THREAD

**Issue by jvansanten** [WIPACrepo/iceprod#245]
I can submit a dataset with the `dataset` field pre-populated in the configuration, and iceprod will happily accept it even if it does not match the actual dataset number. An example is here, where an id of 0 was left over from testing:

https://iceprod2.icecube.wisc.edu/config?dataset_id=O1r99c57luMXl1

Since the dataset number is used for the temporary scratch location, this can make datasets overwrite each other's temporary files.

**Comment by dsschult** [comment]
Huh.  That's supposed to be overwritten always.

(though maybe if you edit the config later, it can be modified)

**Comment by dsschult** [comment]
This should now not be set in new configs, and will always get overwritten by the grid submitter.
