### ISSUE TITLE
Error logs missing

### ISSUE THREAD

**Issue by jcdiazvelez** [WIPACrepo/iceprod#264]
Tasks are marked as having been reset due to errors but there are no logs indicating what the error is.

**Comment by jbstettner** [comment]
Here's an example:
https://iceprod2.icecube.wisc.edu/dataset/253c1272ffcf11e9bf06141877284d92/task/a1c8c184ffd211e98122141877284d92

There is a printout of the stdlog, but it contains confusing output including other job-ids.
The actual stderr does however not reflect what went wrong but only complains about the missing stderr/stdout files at the last re-try of the job

**Comment by dsschult** [comment]
Many changes have happened in this area, so closing this issue.  Create a new issue if there are new problems.
