### ISSUE TITLE
Feature request: dataset priority (relative)

### ISSUE THREAD

**Issue by jcdiazvelez** [WIPACrepo/iceprod#277]
One feature that appears to be missing is the ability to set the priority of a dataset. This should only be relative to a single user's set of datasets.  Other users should not be affected by this. There should be a function on the REST API (and probably on the web page to set this).

**Comment by dsschult** [comment]
Priority is now able to be set on the website, and as a function in the REST API.

The equation currently considers priority relative to both the user's datasets and the group's datasets.  This can (and likely will be) revised as necessary.
