### ISSUE TITLE
Webpage is delayed with what is actually done in submitter

### ISSUE THREAD

**Issue by manuel92780** [WIPACrepo/iceprod#284]
If i click "suspend" (or any command that changes status) on a set of jobs that is "running" on the iceprod webpage,  but "queued" on grafana, the webpage will tell me immediately that the job was suspended. 
However, looking in grafana shows that the jobs remain on "queue" for ~24 hours after getting suspended. This is potentially critical in the cases where the queue is largely filled with the jobs that were suspended.

**Comment by dsschult** [comment]
@manuel92780 
note that I used dataset 21220 for testing, and I think I reset some completed tasks on accident

**Comment by dsschult** [comment]
Reopening: the part about jobs still left on condor is a remaining issue.
