### ISSUE TITLE
Jobs in error state suspending completed tasks

### ISSUE THREAD

**Issue by jcdiazvelez** [WIPACrepo/iceprod#285]
When jobs go into error state, they suspend all tasks even if they have completed. This means that you essentially have to do a hard reset and lose any intermediate work. In the example in the screenshot. These tasks failed at the clsim (CPU) level. For this particular dataset, the genie portion takes about 8hrs and the clsim part takes about 1hr. In order to reset these jobs, we loose the 8hr work from the genie task.

<img width="662" alt="Genie screen shot" src="https://user-images.githubusercontent.com/8840648/86470855-e1416e00-bd01-11ea-812f-dfb9683739e8.png">

**Comment by jvansanten** [comment]
A likely culprit is
https://github.com/WIPACrepo/iceprod/blob/7629ad5f846f87833c9d88bcaca73a80659a8bd7/iceprod/server/scheduled_tasks/dataset_cleanup.py#L83-L90
where you get all jobs in states `errors` or `suspended` and suspend all materialized tasks for those jobs whose states are neither `completed` nor `suspended`. According to
https://github.com/WIPACrepo/iceprod/blob/7629ad5f846f87833c9d88bcaca73a80659a8bd7/iceprod/server/util.py#L22-L23
however, there is no state `completed`, only `complete`.
