### ISSUE TITLE
Publish to PyPI with `wipac-cicd.yml`

### ISSUE THREAD

**Issue by ric-evans** [WIPACrepo/iceprod#307]
We can now use `wipac-rest-tools` and/or `wipac-rest-tools[telemetry]`

This repo is treated as a package by the Indexer (mainly `iceprod.core`).

See https://github.com/WIPACrepo/wipac-dev-tools/issues/20

**Comment by dsschult** [comment]
Depends on https://github.com/WIPACrepo/wipac-dev-py-setup-action/issues/3
