### ISSUE TITLE
Iceprod should not rerun failed jobs

### ISSUE THREAD

**Issue by kjmeagher** [WIPACrepo/iceprod#335]
title was: Iceprod should not rerun jobs if they fail due photons not being stored

If https://github.com/icecube/icetray/pull/3010 is merged into icetray then this will cause jobs which don't have enough space to store all the photons to hard fail with a reasonable error message. This is a good thing but if iceprod immeditally reruns the job there is a chance the second run could succeed creating an energy dependent bias in our simulation. 

Iceprod should detect that icetray failed in this fashion and not try to resubmit jobs.

**Comment by dsschult** [comment]
Talking on slack:
> so I guess what is really wanted is a way to disambiguate between "retry for memory/site reasons" and "this job has an actual failure" and stop the latter
