### ISSUE TITLE
website security

### ISSUE THREAD

**Issue by dsschult** [WIPACrepo/iceprod#45]
(imported from trac: [#850](http://code.icecube.wisc.edu/projects/icecube/ticket/850))

Things to check on:
- secure cookies
- HttpOnly? cookies
- strict transport security
- content security policy
- iframe options
- xss protection
- mime-type sniffing

**Comment by dsschult** [comment]
xss protection and secure cookies are now enabled for the login form. they are probably impossible to implement for jsonrpc, since that also needs to handle job requests.

**Comment by Atavic** [comment]
Info about Mime type sniffing: https://github.com/ipfs/notes/issues/222
