### ISSUE TITLE
dataset submit failures

### ISSUE THREAD

**Issue by dsschult** [WIPACrepo/iceprod#74]
(imported from trac: [#1678](http://code.icecube.wisc.edu/projects/icecube/ticket/1678))

Dataset submit failures are pretty silent from the user's POV. Get better at telling them what is wrong, or at least that an error did occur. I think this is for failures inside the javascript, before it gets to the server (from the advanced submit, probably invalid json or something else wrong with the job config).

**Comment by ddelventhal** [comment]
Number of jobs and JSON parsing are now checked.
